# Generated by Django 4.0.6 on 2022-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('taskname', models.CharField(default='', max_length=100)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
